apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iotdeploymentclaims.iot.example.com
spec:
  group: iot.example.com
  names:
    kind: IoTDeploymentClaim
    plural: iotdeploymentclaims
    singular: iotdeploymentclaim
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              deviceName:
                type: string
              image:
                type: string
