Vagrant.configure("2") do |config|

  # Configurazione della VM
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "k3s-worker-node1"

  # IP statico della VM
  config.vm.network "private_network", ip: "192.168.56.101"

  # Configurazione del provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  # Provisioning della VM
  config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://192.168.56.100:6443 \
    K3S_TOKEN=K10b3e4ccabb6ca91653eee57c3ff0be5ade845877ee07153b80132f42e30e83233::server:c780926d5406d5fce4c059cff1b9918e \
    sh -
  SHELL
end
