Vagrant.configure("2") do |config|

  # Configurazione della VM
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "k3s-server"

  # IP statico della VM
  config.vm.network "private_network", ip: "192.168.56.100"

  # Configurazione del provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # Provisioning della VM
  config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-name k3s-server" sh -
    echo "Node token:"
    sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token.txt
  SHELL
end

