apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iotdevice-composition
spec:
  compositeTypeRef:
    apiVersion: iot.example.com/v1alpha1
    kind: IoTDevice
  patchSets:
    - name: commonLabels
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.labels"
          toFieldPath: "metadata.labels"
  resources:
    - name: managed-iotdevice
      base:
        apiVersion: someprovider.iot/v1
        kind: ManagedIoTDevice
        metadata:
          labels:
            managed-by: crossplane
        spec:
          deviceName: default-device
          configuration: {}
      patches:
        - type: PatchSet
          patchSetName: commonLabels
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.deviceName"
