apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-controller
  template:
    metadata:
      labels:
        app: iot-controller
    spec:
      serviceAccountName: default
      containers:
        - name: iot-controller
          image: myrepo/iot-controller:latest
          imagePullPolicy: IfNotPresent
