apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iotdeviceclaims.iot.example.com
spec:
  group: iot.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deviceType:
                  type: string
                connectivity:
                  type: string
  scope: Namespaced
  names:
    plural: iotdeviceclaims
    singular: iotdeviceclaim
    kind: IoTDeviceClaim
    shortNames:
      - iotclaim