apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iotdevice-composition
spec:
  compositeTypeRef:
    apiVersion: iot.example.com/v1alpha1
    kind: CompositeIoTDevice
  resources:
    - name: iotdevice
      base:
        apiVersion: iot.example.com/v1
        kind: IoTDevice
        metadata:
          namespace: iot-devices
        spec:
          ip: ""
          status: "available"
          lastSeen: ""
      patches:
        - fromFieldPath: "spec.ip"
          toFieldPath: "spec.ip"
        - fromFieldPath: "spec.lastSeen"
          toFieldPath: "spec.lastSeen"
