apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeiotdevices.iot.example.com
spec:
  group: iot.example.com
  names:
    kind: CompositeIoTDevice
    plural: compositeiotdevices
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ip:
                  type: string
                status:
                  type: string
                  enum: ["available", "assigned", "offline", "errored"]
                lastSeen:
                  type: string
                  format: date-time
