apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-devices-deployment
  labels:
    app: iot-devices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iot-devices
  template:
    metadata:
      labels:
        app: iot-devices
    spec:
      containers:
      - name: iot-devices-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iot-devices-service
spec:
  selector:
    app: iot-devices
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
