apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdockerapps.example.org
spec:
  group: example.org
  names:
    kind: XDockerApp
    plural: xdockerapps
  claimNames:
    kind: DockerApp
    plural: dockerapps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              port:
                type: integer
              replicas:
                type: integer
                default: 1
            required:
              - image
              - port
