apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdockercontainers.platform.example.com
spec:
  group: platform.example.com
  names:
    kind: XDockerContainer
    plural: xdockercontainers
  claimNames:
    kind: DockerContainer
    plural: dockercontainers
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  image:
                    type: string
                  port:
                    type: integer
                  envVars:
                    type: object
                    additionalProperties:
                      type: string
            required:
              - image
