apiVersion: v1
kind: Service
metadata:
  name: iot-device-service
  namespace: iot-devices
spec:
  type: NodePort # espone il servizio su tutte le interfacce IP del nodo, 
  # mappa una porta specifica del nodo verso una porta interna del container
  selector:
    app: iot-device
  ports:
    - protocol: TCP
      port: 80         # Porta del Service interna al cluster
      targetPort: 8081 # Porta su cui il Service gira il traffico
      nodePort: 30085  # Porta accessibile dall'esterno (curl http://<node-ip>:30085)
