apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # 🔹 Kubernetes assegna una porta tra 30000-32767
  type: NodePort
