Vagrant.configure("2") do |config|

  # Configurazione della VM
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "k3s-worker-node2"
  
  # IP statico della VM
  config.vm.network "private_network", ip: "192.168.56.10"

  # Configurazione del provider VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  # Token k3s (si ottiene con sudo cat /var/lib/rancher/k3s/server/node-token

  # Provisioning della VM
  config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://192.168.56.1:6443 \
    K3S_TOKEN=K1005348c0124f7380930a2518b92ea410f8ca00f56924b8decc10fb5b41cb1200e::server:caafe02c2fbb964927bc3aff0f71c890 \
    K3S_NODE_ROLE=worker \
    sh -
  SHELL
end

# Imposta il ruolo della VM come worker: kubectl label node worker-node k3s.io/worker=true