apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:         # il Service seleziona i pod con l'etichetta app: nginx, 
                    # che corrisponde ai pod creati dal Deployment di Nginx.
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 #  consente di accedere al servizio dall'esterno del cluster Kubernetes sulla porta 30080 (TCP).
  type: LoadBalancer
